TEST_PROMPTS = [
    "Explain recursion simply.",
    "What is AI in 2 sentences?",
    "Write a Python function to reverse a string.",
    "Summarize the benefits of running AI models locally.",
    "Explain the difference between latency and throughput.",
    "What is JSON validation and why is it useful?",
    "Write a short email asking for a project status update.",
    "Explain Docker to a beginner.",
    "What is the difference between SQL and NoSQL databases?",
    "Write a Python function to check if a number is prime.",
    "Explain REST APIs in simple terms.",
    "Summarize this sentence: Local AI models improve privacy but may be slower.",
    "List three pros and cons of using small language models.",
    "Explain what a tokenizer does in an LLM.",
    "Write a simple unit test example in Python.",
    "What is caching and why does it improve performance?",
    "Explain the difference between CPU and GPU inference.",
    "Convert this into JSON: name Vijay, role developer, skill Python.",
    "Explain what model quantization means.",
    "Write a short paragraph about data privacy.",
    "What is a cold start in software systems?",
    "Explain why output length affects latency.",
    "Write pseudocode for a login system.",
    "Compare local inference and cloud API inference.",
    "Explain what temperature means in language models."
]